_BASE_CARDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10]
_NUMBER_OF_CARDS_OF_THE_SAME_TYPE = 4
_NUMBER_OF_DECKS = 6
DECK = _BASE_CARDS * _NUMBER_OF_CARDS_OF_THE_SAME_TYPE * _NUMBER_OF_DECKS

DECK.sort()
